# 1. The logarithm of `x` is only defined for `x > 0`, so 0 is outside fo the 
#    domain of the function.
# 2. You get an error of type "ValueError", indicating that the function received 
#    an inappropriate argument value. The additional message "math domain error" 
#    makes it clearer what the problem is.